version: '3.8'

networks:
  web:
    driver: bridge

services:
  chrome:
    image: selenium/standalone-chrome-debug:latest
    # Debug version enables VNC ability
    ports:
      - '4444:4444'
      - '5900:5900'
    # Bind selenium port & VNC port
#    logging:
#      driver: none
      # Disable noisy logs.
    networks:
      - default
