version: '3.3'

networks:
  web:
    driver: bridge

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  app:
    depends_on:
      - db
      - worker
      - chrome
    build: .
    command: bundle exec rails s -b 0.0.0.0
    stdin_open: true
    tty: true
    environment:
      - RAILS_ENV=development
      - BOOTSNAP=true
    volumes:
      - .:/app
    env_file:
    - .env.dev
    ports:
      - "3000:3000"

  worker:
    depends_on:
      - redis
    build: .
    command: bundle exec sidekiq
    stdin_open: true
    tty: true
    environment:
      - RAILS_ENV=development
      - BOOTSNAP=true
    volumes:
      - .:/app
    env_file:
      - .env.dev
    networks:
      - default

  chrome:
    image: selenium/standalone-chrome-debug:latest
    # Debug version enables VNC ability
    environment:
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    shm_size: 2g
    privileged: true
    volumes:
      - /dev/shm:/dev/shm
      - ./config/chrome_profile:/home/seluser/chrome_profile
    ports:
      - '4444:4444'
      - '5900:5900'
      # Bind selenium port & VNC port
    logging:
      driver: none
      # Disable noisy logs.

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres: