version: '3.3'

services:
  db:
    image: postgres
    hostname: db
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file: .env.prod
    ports:
      - "3000:3000"

    command: bundle exec rails s -b 0.0.0.0

  chrome:
    image: selenium/standalone-chrome-debug:latest
    # Debug version enables VNC ability
    ports:
      - '4444:4444'
      - '5900:5900'
      # Bind selenium port & VNC port
    volumes:
      - ./config/chrome_profile:/home/seluser/chrome_profile
    logging:
      driver: none
      # Disable noisy logs.

  redis:
    image: redis:alpine
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    ports:
      - '6379:6379'
    restart: always


  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    env_file: .env.prod

volumes:
  postgres:
  gem_cache:
  redis: