version: '3.3'

services:
  db:
    image: postgres
    hostname: db
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

#  sidekiq:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#      - redis
#    volumes:
#      - .:/app
#      - gem_cache:/usr/local/bundle/gems
#    env_file: .env
#    command: bundle exec sidekiq -C config/sidekiq.yml

  chrome:
    image: selenium/standalone-chrome-debug:latest
    # Debug version enables VNC ability
    ports:
      - '4444:4444'
      - '5900:5900'
      # Bind selenium port & VNC port
      #    logging:
      #      driver: none
      # Disable noisy logs.
    networks:
      - default

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    env_file:
    - .env

volumes:
  postgres:
  gem_cache: