aliexpress:
  browser_type: 'Js'
  url: https://aliexpress.com
  q: https://aliexpress.ru/wholesale?catId=&SearchText=
  search_bar_class: SearchHeader_SearchInput
  search_selector:
    name: 'SearchText'
  found_elements_class: SearchProductFeed
  product_list_css: '[class^="SearchProductFeed"] ul li ul li'
  attributes:
    price_original: '[class^="SearchProductFeed_Price__"]'
    final_price: '[class^="SearchProductFeed_Price__finalPriceContainer__"]'
    full_price: '[class^="SearchProductFeed_Price__fullPrice__"]'
    link: '[class^="SearchProductFeed_GalleryCard__title"] a'
    title: '[class^="SearchProductFeed_GalleryCard__title"] a'
    delivery: '[class^="SearchProductFeed_Price__freeDelivery__"]'
    sale_count: '[class^="SearchProductFeed_Quality__quality"] a'


yandex:
  q: https://yandex.ru/search/?lr=213&text=
  url: https://yandex.ru
  browser_type: 'html'

yandex_market:
#  browser_type: 'Js'
  attributes:
    row: "data-zone-name='OfferSnippet'"
    title_data: "data-zone-name='title'"
    price_data: "data-autotest-currency='₽'"
ozon:
  attributes:
    title_css: 'h1'
    price_data: "data-widget='webSale'"




